instance:
  _target_: pytorch_lightning.Trainer
  checkpoint_callback: True
  default_root_dir: null
  gradient_clip_val: 0.0
  num_processes: 1
  gpus: 1
  log_gpu_memory: null
  overfit_batches: 0.0
  fast_dev_run: False
  max_epochs: 10
  min_epochs: 1
  log_every_n_steps: 150
  precision: 32
  num_sanity_val_steps: 2
  profiler: null
  auto_lr_find: False

loggers:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: "tensorboard/"
    default_hp_metric: false
    name: ""
    version: ""
    log_graph: false
    prefix: ""
  - _target_: pytorch_lightning.loggers.wandb.WandbLogger
    entity: "butterflies"
    project: "dev"
    offline: False
    id: null # pass correct id to resume experiment!
    log_model: False
    prefix: ""
    job_type: "train"
    group: ""
    tags: [ ]


callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val-loss"
    dirpath: "checkpoints/"
    save_last: true
    filename: "{epoch:03}-{val-total-loss:.4f}"
    save_top_k: 1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
    log_momentum: True
